api_key: "sk_car_LDui6S3Df4W6HhbSZtEsXn"

api_url: "https://api.cartesia.ai/voice-changer/bytes"

headers:
  Cartesia-Version: "2025-04-16"
  Authorization: "Bearer {{api_key}}"

payload:
  voice[id]: "694f9389-aac1-45b6-b726-9d9369183238"
  output_format[container]: "mp3"        
  output_format[sample_rate]: "44100"
  output_format[bit_rate]: "256000"     